# Form implementation generated from reading ui file '/Users/erikray/Developer/Lab 4 DB/design.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


